lab07/models.py
import click
from flask import current_app, g
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import mapped_column
from sqlalchemy import Integer, String


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    user_id = mapped_column(Integer, primary_key=True, autoincrement=True)
    first_name = mapped_column(String, nullable=False)
    last_name = mapped_column(String, nullable=False)
    email = mapped_column(String, nullable=False, unique=True)
    password = mapped_column(String, nullable=False)  # never do this. this is bad.


db = SQLAlchemy(model_class=Base)


def init_app(app):
    db.init_app(app)
    with app.app_context():
        db.create_all()

lab07/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy


def create_app():
    app = Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY="dev",
        SQLALCHEMY_DATABASE_URI="sqlite:///database.sqlite",
    )

    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import models

    models.init_app(app)

    from . import routes

    app.register_blueprint(routes.bp)

    return app

lab07/routes.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_sqlalchemy import SQLAlchemy

from lab07.models import User, db


bp = Blueprint("main", __name__)


@bp.route("/", methods=["GET"])
def index():
    # if user is in session pass to template
    user = None
    if "user_id" in session:
        user = db.session.query(User).get(session.get("user_id"))

    return render_template("index.html", user=user)


@bp.route("/login", methods=["GET"])
def login():
    if "user_id" in session:
        flash("Already logged in")
        return redirect(url_for("main.index"))
    return render_template("login.html")


@bp.route("/login", methods=["POST"])
def login_post():
    email = request.form["email"]
    password = request.form["password"]

    user = db.session.query(User).filter_by(email=email, password=password).first()
    if not user:
        flash("Invalid email or password")
        return redirect(url_for("main.login"))

    session["user_id"] = user.user_id  # never do this. this is bad.
    flash("Logged in")
    return redirect(url_for("main.secretpage"))


@bp.route("/logout", methods=["GET"])
def logout():
    session.pop("user_id", None)
    flash("Logged out")
    return redirect(url_for("main.index"))


@bp.route("/register", methods=["GET"])
def register():
    if "user_id" in session:
        flash("Already logged in")
        return redirect(url_for("main.index"))
    return render_template("register.html")


@bp.route("/register", methods=["POST"])
def register_post():
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    email = request.form["email"]
    password = request.form["password"]

    # ensure email not already used
    user = db.session.query(User).filter_by(email=email).first()
    if user:
        flash("Email address already exists")
        return redirect(url_for("main.register"))

    new_user = User(
        first_name=first_name, last_name=last_name, email=email, password=password
    )
    db.session.add(new_user)
    db.session.commit()

    flash("Registration successful")
    return redirect(url_for("main.thankyou"))


@bp.route("/secretpage", methods=["GET"])
def secretpage():
    if "user_id" not in session:
        flash("Must be logged in to view this page")
        return redirect(url_for("main.login"))

    user = db.session.query(User).get(session.get("user_id"))
    if not user:
        flash("Must be logged in to view this page")
        return redirect(url_for("main.login"))

    return render_template("secretpage.html", user=user)


@bp.route("/thankyou", methods=["GET"])
def thankyou():
    users = db.session.query(User).all()
    return render_template("thankyou.html", users=users)

lab07/templates/base.html
<!DOCTYPE html>
<head>
    <title>CS 421 - Lab 07</title>
    <link
        rel="stylesheet"
        href="https://unpkg.com/modern-normalize@2.0.0/modern-normalize.css"
    />
    <style>
        .flash {
            background-color: #c7e4ff;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin: 10px 0;
            padding: 10px;
        }
    </style>
</head>
<body style="margin: 0 2em">
    <nav style="display: flex; flex-direction: column; gap: 1em">
        <div
            style="
                display: flex;
                flex-direction: row;
                gap: 1em;
                align-items: center;
            "
        >
            <h1 style="margin-bottom: 0">CS 421 - Lab 07</h1>
            {% if user %}
            <p style="margin-bottom: 0">Logged in as {{ user.email }}</p>
            {% endif %}
        </div>
        <div style="display: flex; flex-direction: column; gap: 0.25em">
            <a href="{{ url_for('main.index') }}">Home</a>
            <a href="{{ url_for('main.secretpage') }}">Secret Page</a>
            {% if not user %}<a href="{{ url_for('main.login') }}">Login</a>
            <a href="{{ url_for('main.register') }}">Register</a>{% else %}
            <a href="{{ url_for('main.logout') }}">Logout</a>{% endif %}
        </div>
    </nav>
    <section class="content">
        <header>{% block header %}{% endblock %}</header>
        {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
        {% endfor %} {% block content %}{% endblock %}
    </section>

    <p>
        <a
            href="https://unix.stackexchange.com/questions/92185/whats-the-story-behind-super-cow-powers"
            >This webpage does not have Super Cow Powers.</a
        >
    </p>
</body>

lab07/templates/index.html
{% extends 'base.html' %} {% block content %}
<p>View my secret page <a href="{{ url_for('main.secretpage') }}">here</a>!</p>
{% endblock %}

lab07/templates/login.html
{% extends 'base.html' %} {% block content %}
<h2>Login</h2>
<form method="POST">
    <label for="email">Email</label>
    <input type="text" id="email" name="email" required />
    <label for="password">Password</label>
    <input type="password" id="password" name="password" required />
    <button type="submit">Login</button>
</form>

{% endblock %}

lab07/templates/register.html
{% extends 'base.html' %} {% block content %}
<h2>Register</h2>
<form style="display: flex; flex-direction: column; gap: 1em" method="POST">
    <div>
        <label for="first_name">First Name</label>
        <input type="text" id="first_name" name="first_name" required />
        <label for="last_name">Last Name</label>
        <input type="text" id="last_name" name="last_name" required />
    </div>
    <div>
        <label for="email">Email</label>
        <input type="email" id="email" name="email" required />
    </div>
    <div>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" required />
        <label for="confirm_password">Confirm Password</label>
        <input
            type="password"
            id="confirm_password"
            name="confirm_password"
            required
        />
    </div>
    <div>
        <button type="submit">Register</button>
    </div>
</form>

<script>
    const form = document.querySelector("form");
    form.addEventListener("submit", async (e) => {
        e.preventDefault();

        form.checkValidity();

        // verify password
        const password = document.getElementById("password").value;
        const confirm_password =
            document.getElementById("confirm_password").value;
        if (password !== confirm_password) {
            alert("Passwords do not match");
            return;
        }

        form.submit();
    });
</script>
{% endblock %}

lab07/templates/secretpage.html
{% extends 'base.html' %} {% block content %}
<h2>Secret Page</h2>
<p>Welcome to the secret page!</p>
<p>You're logged in as {{ user.first_name }} {{ user.last_name }}.</p>

<img
    src="https://media1.tenor.com/m/MArtmCi0hlMAAAAC/computer-science-c-code.gif"
/>
{% endblock %}

lab07/templates/thankyou.html
{% extends 'base.html' %} {% block content %}
<h2>Thank you</h2>
{% for user in users %}
<p>Thank you, {{ user.first_name }} {{ user.last_name }}, for registering!</p>
{% endfor %} {% endblock %}